name: Pull request

on:
  pull_request:


jobs:
  test:
    uses: traittech/nova-wallet-android/.github/workflows/android_build.yml@develop
    with:
      branch: ${{github.head_ref}}
    secrets: inherit
